server:
  port: 600
  use-forward-headers: true
  servlet:
    session:
      timeout: 86400s
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/holer?createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    platform: mysql
    #schema: classpath:conf/holer-schema.sql
    data: classpath:conf/holer-data.sql
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
    separator: ;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
logging:
  level:
    root: error
    org.holer: warn
holer:
  server:
    host: 0.0.0.0
    port: 6060
  sslserver:
    enable: true
    host: 0.0.0.0
    port: 6443
  domain:
    name: your-domain.com
  nginx:
    #home: /usr/local/nginx
    home: C:/nginx
  license:
    serialno: 
